spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lancamento_contas_test?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo&useLegacyDatetimeCode=false
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
